apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: atsea
        - name: POSTGRES_PASSWORD_FILE
          value: /run/secrets/postgres_password
        - name: POSTGRES_USER
          value: gordonuser
        image: atsea_db
        name: database
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
status: {}
